// Task-1: Hide notify-section
hideNotifySection();

//Task-2: Generate 4-digit random number when generate-btn is clicked and show it in
document.getElementsByClassName("generate-btn")[0]
    .addEventListener("click", (event) => {
        hideNotifySection();
        document.getElementsByClassName("form-control")[1].value = "";
        let randomnumber = getRandomNumberInRange(9999, 1000);
        document.getElementsByClassName("form-control")[0].value = randomnumber;
    });

//Task-3: Keyboard handling
document.getElementsByClassName("calc-body")[0]
    .addEventListener("click", (event) => {
        const element = event.target;
        let input = document.getElementsByClassName("form-control")[1].value;

        if(element.classList.contains("backspace")) { 
                              // This one is for extra marks
            input = input.substr(0, input.length-1);
            document.getElementsByClassName("form-control")[1].value = input;

        } else if(element.classList.contains("clear")) {               // This one is for extra marks

            document.getElementsByClassName("form-control")[1].value = "";

        } else if(element.classList.contains("submit-btn")) {

            // Task-4: Submit and respose according to the output
            const autoGeneratedNumber = document.getElementsByClassName("form-control")[0].value;
            console.log(autoGeneratedNumber);
            console.log(input);

            if(input === autoGeneratedNumber) {
                displayMatched();
            } else {
                displayNotMatched();
                let tryRemamin = document.getElementById("try-remain").innerText;
                tryRemamin = Number(tryRemamin)-1;
                document.getElementById("try-remain").innerText = tryRemamin;
                if(tryRemamin === 0) element.disabled = true;
            }
            // Task-4 ended

        } else if(element.classList.contains("button")) {

            const digit = element.innerText;
            input =  input + digit;
            document.getElementsByClassName("form-control")[1].value = input;

        }
    });



// Functions
function hideNotifySection() {
    document.getElementById("not-matched").style.display = "none";
    document.getElementById("matched").style.display = "none";    
}

function displayMatched() {
    document.getElementById("not-matched").style.display = "none";
    document.getElementById("matched").style.display = "block"; 
}

function displayNotMatched() {
    document.getElementById("not-matched").style.display = "block";
    document.getElementById("matched").style.display = "none"; 
}

function getRandomNumberInRange(maximum, minimum) {
    return Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;
}
